### ISSUE TITLE
File transfers are failing.

### ISSUE THREAD

**Issue by Mutnick** [eLvErDe/nicotine-plus#19]
Some encoding issues are preventing people from downloading files - this is not good.

I tested running nicotine-plus on Windows, using a remote client (SlskQT, also on Windows) to request a file from the nicotine-plus client. The file transfer fails due to a problem with nicotine-plus:

"TypeError: String or Integer object expected for key, unicode found" 

I found that correctPath(self, path) in shares.py was being called with 'path' encoded as unicode, whereas the shelve keys are encoded string! Obviously, this leads to the TypeError.

Functionality of correctPath() is not even needed when running nicotine-plus on windows.  The most straightforward fix is adding a nope-out to the start of correctPath:
```
if win32:
    return
````

Do you have a better fix?

**Comment by gfarmerfr** [comment]
I'm not familiar with this part of nicotine at the moment but i will take a look at it.
From what i see this might have been be introduced as a workaround for a bug in SLSK client in this commit: https://github.com/eLvErDe/nicotine-plus/commit/be9dc4acc854b55cf1c5998a1f480d920198917b
Might be a good idea to look at the changelog of the official client to see if there is a reference to something similar.

**Comment by gfarmerfr** [comment]
I've checked the changelog of the official SLSK client and no bugfix of that sort is mentioned.
From the commit timestamp from Quinox it might have been a workaround the old SoulSeekNS client that is still in the code base.
I will make a branch that partially revert the offending bits of the commit for testing purposes.

I suppose the line raising the exception you referer to is this one in the correctPath function ?

```
try:
      return self.config.sections["transfers"]["lowercase"][path]
```

**Comment by gfarmerfr** [comment]
Hi @Mutnick 
Here is the branch: https://github.com/gfarmerfr/nicotine-plus/tree/fix-file-transfers-correctPath.
Could you have a look at it ?
I've reverted the whole lowercase hack since it seems it was a workaround for a version of SoulseekNS that is deprecated.

**Comment by Mutnick** [comment]
Looks good to me.

**Comment by gfarmerfr** [comment]
Thx. Merged on master.
