### ISSUE TITLE
Hidden directory files now showing up in file shares (Windows)

### ISSUE THREAD

**Issue by Mutnick** [eLvErDe/nicotine-plus#23]
I have directories both with attrib +h and also that start with a dot. In the past this prevented sharing on both the official soulseek clients (which respect the attribute) and with nicotine+ (which in the past hid the .directories).

The hidden .directory files are now showing up in shares when running nicotine+ on windows.

**Comment by Mutnick** [comment]
This is both a security issue and a hassle as to actually prevent sharing I'd have to move such a directory out of it's normal location.

**Comment by gfarmerfr** [comment]
Hi @mutnick,

I can reintroduce this easily.
I will revert this commit tomorrow: https://github.com/eLvErDe/nicotine-plus/commit/60deb7034dd09ab15662fddf2e17fc25fa6d053d.

Btw I've not seen any code in the code base dealing with the +h attribute as far I know.
That would be the clean way of doing it in nicotine+ I agree.
I will have a look at it.

**Comment by gfarmerfr** [comment]
Could you check this branch : https://github.com/gfarmerfr/nicotine-plus/tree/fix-hidden-directories-windows ?
I've reverted the commit so dot directories are excluded and on top of that I've added a check for the hidden attribute on Windows that will exclude those too.
Seems to work well on Win7.

**Comment by Mutnick** [comment]
> Could you check this branch : https://github.com/gfarmerfr/nicotine-plus/tree/fix-hidden-directories-windows ?

It appears a required module wasn't included:

ImportError: No module named win32file

**Comment by gfarmerfr** [comment]
Yes I've just found it too. I had the 'pypiwin32' module installed which include win32file as a side effect of having pyinstaller on my Win7 box.
What do you think:
Should we make 'pypiwin32' a requirement on Windows ?
Or should we try to import it and do nothing if it fails (and loose the ability to hide attrib +h file) ?

**Comment by Mutnick** [comment]
I think for now it's adequate that .directory behavior is consistent across platforms and consistent with previous nicotine+ functionality: dot directories should be hidden.

It would be good to have that modules functionality for the additional checking, but yes make it optional.

**Comment by Mutnick** [comment]
Also if we eventually get to python 3.5 it looks a bit more straightforward without additional modules, see for example the is_hidden() here https://bugs.python.org/issue21719

**Comment by gfarmerfr** [comment]
Yes it would be easier for sure :) Thx for the link.

Btw i've just updated the branch with the try/expect/else for the optional win32file.

**Comment by gfarmerfr** [comment]
Hi @Mutnick

Have you tested the refreshed branch ? For me it works fine.
Can I go ahead and merged it ?

**Comment by Mutnick** [comment]
Yes this looks good, thanks.

**Comment by gfarmerfr** [comment]
Done. Thx :)
