### ISSUE TITLE
upnp functionality is used despite being config'd as False

### ISSUE THREAD

**Issue by Mutnick** [eLvErDe/nicotine-plus#24]
In frame.py's OnFirstConnect function there are initializations and checks of upnp functionality even when upnp is configured as False (and such functionality is not desired or needed)

Please relocate

`` if self.np.config.sections["server"]["upnp"]:
``

to the very start of OnFirstConnect()

This is an issue as the reworked code broke the ability of the user to Torify Nicotine+.

**Comment by gfarmerfr** [comment]
Yes I can move this line at the start of the function that's not a problem.
In this case we might have a look too at settingswindow.py at the end of the SetSettings function of the ServerFrame class.
What I'm trying to understand is what would break a Torify Nicotine+ ?
The line you're referring to 'upnp.IsPossible()' only checks if either the upnpc binary or python miniupnpc module is available and don't send any packet on the network as far as I know.

**Comment by gfarmerfr** [comment]
I've relocate the line at the top of the function OnFirstConnect() in frame.py.

I've also found another line to relocate in the upnp.py \__init__ function:
```
# Local LAN IP
self.internalipaddress = gethostbyname(gethostname())
```

This line was doing a NS lookup and i've pushed it back down to the function actually doing the port mapping so it's not called at initialization/check times. See https://github.com/gfarmerfr/nicotine-plus/commit/710621bc69ffb9179123bd94d0f5675996d0b208 in https://github.com/gfarmerfr/nicotine-plus/tree/avoid-unwanted-traffic-upnp

**Comment by Mutnick** [comment]
The error occurs when resolving the host name.

upnp = UPnPPortMapping() leading to the gethostbyname(gethostname()) is where the error occurs.

On windows, gaierror: [Errno 11003] getaddrinfo failed
On a Debian based machine, gaierror: [Errno -2] Name or service not known

I'll look into this further but the point remains that if someone doesn't want the upnp functionality for whatever reason, there is no need to be calling it at all.

**Comment by gfarmerfr** [comment]
Just posted a few seconds ago :)
Could you check my last post and tells me what do you think of the solution ?

**Comment by Mutnick** [comment]
Thank you, looks good.

**Comment by gfarmerfr** [comment]
Merged into master.
